# Aliases
alias cl='ssh -Y ttl4@ssh.clear.rice.edu'
alias wcd='cd /run/media/tamtale/04846F03846EF698'
alias ricevpn='sudo vpnc RiceVPN'
alias agenda='gcalcli agenda --calendar Tam --calendar plan --calendar tests/quizzes'
alias woman='man'
alias rotate='xrandr --output DP-2 --rotate '
alias mountu='sudo mount -t cifs -o username=ttl4,dom=ADRICE //storage.rice.edu/t-home/ttl4 /home/tamtale/udrive'
alias br='xrandr --output eDP-1 --brightness'
alias plan='gcalcli -calendar plan agenda today tomorrow'
alias monitor='xrandr --output DP-2 --right-of eDP-1 --auto && i3-msg restart'
alias rg='ranger'
